In [1]:
import numpy as np
import pandas as pd

customers = ['A', 'B', 'C', 'D', 'E']

x1 = np.array([1, 2, 3, 5, 6], dtype=float)
x2 = np.array([4, 3, 7, 2, 6], dtype=float)
y = np.array([0, 0, 1, 1, 1], dtype=float)

m1 = 0.8
m2 = 0.4
b = -4.0

eta = 0.1

print("Dataset and parameters loaded successfully!")
print("m1 =", m1)
print("m2 =", m2)
print("b  =", b)
print("Learning rate =", eta)

Dataset and parameters loaded successfully!
m1 = 0.8
m2 = 0.4
b  = -4.0
Learning rate = 0.1

In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

print("Sigmoid function ready!")

Sigmoid function ready!

In [3]:
z = m1*x1 + m2*x2 + b
y_pred = sigmoid(z)

task1 = pd.DataFrame({
    'Customer': customers,
    'x1 Time': x1,
    'x2 Pages': x2,
    'y Actual': y,
    'z Score': z,
    'Predicted Probability': y_pred
})

display(task1.round(6))

  Customer  x1 Time  x2 Pages  y Actual  z Score  Predicted Probability
0        A      1.0       4.0       0.0     -1.6               0.167982
1        B      2.0       3.0       0.0     -1.2               0.231475
2        C      3.0       7.0       1.0      1.2               0.768525
3        D      5.0       2.0       1.0      0.8               0.689974
4        E      6.0       6.0       1.0      3.2               0.960834

In [4]:
loss = -(y * np.log(y_pred) + (1-y) * np.log(1-y_pred))

average_loss = np.mean(loss)

task2 = pd.DataFrame({
    'Customer': customers,
    'x1 Time': x1,
    'x2 Pages': x2,
    'y Actual': y,
    'Predicted Probability': y_pred,
    'Loss': loss
})

display(task2.round(6))

print("Average BCE Loss =", round(average_loss, 6))

  Customer  x1 Time  x2 Pages  y Actual  Predicted Probability      Loss
0        A      1.0       4.0       0.0               0.167982  0.183901
1        B      2.0       3.0       0.0               0.231475  0.263282
2        C      3.0       7.0       1.0               0.768525  0.263282
3        D      5.0       2.0       1.0               0.689974  0.371101
4        E      6.0       6.0       1.0               0.960834  0.039953

Average BCE Loss = 0.224304

In [5]:
dm1 = np.mean((y_pred - y) * x1)
dm2 = np.mean((y_pred - y) * x2)
db = np.mean(y_pred - y)

print("dL/dm1 =", dm1)
print("dL/dm2 =", dm2)
print("dL/db =", db)

new_m1 = m1 - eta * dm1
new_m2 = m2 - eta * dm2
new_b = b - eta * db

print("New m1 =", new_m1)
print("New m2 =", new_m2)
print("New b =", new_b)

dL/dm1 = -0.3697231065554859
dL/dm2 = -0.22180395621299728
dL/db = -0.0362419253606152
New m1 = 0.8369723106555487
New m2 = 0.4221803956212998
New b = -3.9963758074639384

In [6]:
new_z = new_m1*x1 + new_m2*x2 + new_b
new_y_pred = sigmoid(new_z)

task4 = pd.DataFrame({
    'Customer': customers,
    'x1 Time': x1,
    'x2 Pages': x2,
    'y Actual': y,
    'New Probability': new_y_pred
})

display(task4.round(6))

  Customer  x1 Time  x2 Pages  y Actual  New Probability
0        A      1.0       4.0       0.0         0.186839
1        B      2.0       3.0       0.0         0.258096
2        C      3.0       7.0       1.0         0.813028
3        D      5.0       2.0       1.0         0.737467
4        E      6.0       6.0       1.0         0.972308

In [7]:
new_loss = -(y * np.log(new_y_pred) +
             (1-y) * np.log(1-new_y_pred))

new_average_loss = np.mean(new_loss)

task5 = pd.DataFrame({
    'Customer': customers,
    'New Probability': new_y_pred,
    'New Loss': new_loss
})

display(task5.round(6))

print("New Average BCE Loss =", round(new_average_loss, 6))

  Customer  New Probability  New Loss
0        A         0.186839  0.206826
1        B         0.258096  0.298535
2        C         0.813028  0.206990
3        D         0.737467  0.304533
4        E         0.972308  0.028082

New Average BCE Loss = 0.208993